### ISSUE TITLE
Error when running with Karma

### ISSUE THREAD

**Issue by micronaut** [robertknight/babel-plugin-mockable-imports#107]
Hi, I am using the plugin with Karma and I am getting this error _**You appear to be using a native ECMAScript module plugin, which is only supported when running Babel asynchronously**_.  I tried using version 1.8.0 but that gives an error that **_module is not defined_**.

I haven't been able to find a solution to the asynchronous Babel issue and was wondering if anyone know how to fix this.  Thanks.

**Comment by robertknight** [comment]
It sounds like Babel is running inside the browser to transpile code. What I would recommend doing instead is creating a bundle with your test code, using the same bundler (Webpack, Rollup etc.) that you use for production, and then configuring Karma to load that bundle. The big advantage of this approach is that you can actually inspect the compiled bundle of code in case something doesn't work.

As an example, the main application I work on uses a [Rollup config](https://github.com/hypothesis/client/blob/main/rollup-tests.config.mjs) to create a bundle of tests in a known location on disk, which are then run using a simple [Karma config](https://github.com/hypothesis/client/blob/b71396be6934822bf17d69712f8e0363a9ede899/src/karma.config.js#L18).

**Comment by micronaut** [comment]
Thanks @robertknight !  I will give that a try.

**Comment by mk-pmb** [comment]
I had the same issue just now with nodejs v16, and solved it by downgrading babel's dependency module `to-fast-properties` from v4 to v3.
