### ISSUE TITLE
Conflict with EmotionCSS babel plugin

### ISSUE THREAD

**Issue by eugenet8k** [robertknight/babel-plugin-mockable-imports#34]
Did you guys have anyone else reporting this issue with EmotionCSS (https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin)

Generated code 
```js
/* provided dependency */ var _ = __webpack_require__(/*! lodash */ "./node_modules/lodash/lodash.js");

$imports.$add("_css", "@emotion/react", "css", _emotion_react__WEBPACK_IMPORTED_MODULE_0__.css);

const $imports = new babel_plugin_mockable_imports_lib_helpers__WEBPACK_IMPORTED_MODULE_1__.ImportMap();

function _EMOTION_STRINGIFIED_CSS_ERROR__() { return "You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."; }


$imports.$add("useContext", "react", "useContext", react__WEBPACK_IMPORTED_MODULE_2__.useContext);
$imports.$add("useCallback", "react", "useCallback", react__WEBPACK_IMPORTED_MODULE_2__.useCallback);

```

this breaks as `$import ` defined after EmotionCSS does it job.

Babel plugins look like:

```
plugins = {
  development: [
      '@emotion',
      'mockable-imports',
      '@babel/plugin-proposal-class-properties'
  ]
}
```

I tried to change the order of `mockable-imports` but it didn't help

**Comment by robertknight** [comment]
Thank-you for the report. I don't know if anyone else has tried to use Emotion together with this plugin. What would be helpful here is if you could reduce this down to a minimal test case, preferably one that consists of a small component and a minimal Babel config that uses the @emotion and mockable-imports Babel plugins. In other words, not using other Babel plugins or Webpack if possible.

**Comment by eugenet8k** [comment]
@robertknight thanks for the suggestion of preparing the minimum reproducible env. I got really deep into building two examples, where only `babel` is used, or `babel` + `webpack`. I was able to reproduce the mentioned error with  the `webpack` based build, but comparing to the result of cleaner `babel` build perhaps might help to identify the problem.

My repo is https://github.com/eugenet8k/conflict-with-emotioncss-babel-plugin

To test `babel` based scenario:

```
npm install
npm run build:babel
npm run start:babel
```

we get:
```
> conflict-with-emotioncss-babel-plugin@1.0.0 start:babel
> node dist/babel/index.js

Hello from mocked World
```

Assuming the mocked function (https://github.com/eugenet8k/conflict-with-emotioncss-babel-plugin/blob/master/src/index.js)

With `webpack` + `babel` build I get a similar to originally posted error:

```
npm install
npm run build:webpack
npm run start:webpack
```

we get:
```
> conflict-with-emotioncss-babel-plugin@1.0.0 start:webpack
> node dist/webpack/main.js

/Users/user/Git/conflict-with-emotioncss-babel-plugin/dist/webpack/main.js:17
$imports.$add("_styled", "@emotion/styled/base", "default", _emotion_styled_base__WEBPACK_IMPORTED_MODULE_0__.default);
^

ReferenceError: $imports is not defined
    at Object../src/flex.js (/Users/user/Git/conflict-with-emotioncss-babel-plugin/dist/webpack/main.js:17:1)
    at __webpack_require__ (/Users/user/Git/conflict-with-emotioncss-babel-plugin/dist/webpack/main.js:170:41)
```

So the built file `main.js` has all my components together and here is the line with error https://github.com/eugenet8k/conflict-with-emotioncss-babel-plugin/blob/master/dist/webpack/main.js#L17

```
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
/* harmony import */ var _emotion_styled_base__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @emotion/styled/base */ "./node_modules/@emotion/styled/base/dist/emotion-styled-base.esm.js");

$imports.$add("_styled", "@emotion/styled/base", "default", _emotion_styled_base__WEBPACK_IMPORTED_MODULE_0__.default);

function _EMOTION_STRINGIFIED_CSS_ERROR__() { return "You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."; }

const Flex = (0,_emotion_styled_base__WEBPACK_IMPORTED_MODULE_0__.default)("div",  false ? 0 : {
  target: "e1o54d4y0",
  label: "Flex"
})
```

we see `$imports.$add` without `$imports` being defined. So looking at the same built file with babel only https://github.com/eugenet8k/conflict-with-emotioncss-babel-plugin/blob/master/dist/babel/flex.js:

```
"use strict";

exports.__esModule = true;
exports.default = void 0;

var _base = _interopRequireDefault(require("@emotion/styled/base"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _EMOTION_STRINGIFIED_CSS_ERROR__() { return "You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."; }

const Flex = (0, _base.default)("div", process.env.NODE_ENV === "production" ? {
  target: "e1o54d4y0"
}
```

I see that there are not `$import` mocks generated at all! Could that be the reason for the `webpack` build failure?

**Comment by eugenet8k** [comment]
@robertknight does it seem like the example is sufficient to reproduce the issue? I wonder if that's because the EmotionCSS uses hoisted imports? If you guys aren't going to look at this any time soon, I guess I could give it a shot trying to debug your lib. Your solution for mocking is great and it would allow us to use module mocking without moving to Jest or making dirty hacks around webpack moduling system to allow module export stubs.

**Comment by robertknight** [comment]
>  If you guys aren't going to look at this any time soon, I guess I could give it a shot trying to debug your lib.

Hello @eugenet8k - I've been quite preoccupied with work recently, so if you are able to have a go at debugging this yourself that would be great. The code that is supposed to generate the `const $imports = ...` declaration at the top of the file is here: https://github.com/robertknight/babel-plugin-mockable-imports/blob/b2242ea99cf788e90b9b2006e9a77334c4a97ba9/index.js#L224
