### ISSUE TITLE
Remove CommonJS support

### ISSUE THREAD

**Issue by robertknight** [robertknight/babel-plugin-mockable-imports#55]
The projects for which this plugin was originally written have since transitioned all their code to ES modules, so no longer have a need for CommonJS support. I plan to create a major release at some point which removes support for CommonJS to simplify ongoing maintenance.

Note that this only affects modules that are transformed by this plugin, not other scripts in the project or test modules.

**Comment by pedrohcdo** [comment]
Can you explain me how do you used your ES plugin on .babelrc? I tried a lot of configurations but nothing works, everytime i receive this: You appear to be using a native ECMAScript module plugin, which is only supported when running Babel asynchronously.

**Comment by robertknight** [comment]
I don't think the problem is with the .babelrc config. Per the error message:

>  You appear to be using a native ECMAScript module plugin, <ins>which is only supported when running Babel asynchronously.</ins>

How are you running Babel on your code?
